---
# https://taskfile.dev

version: "3"

vars: {}

env: {}

tasks:
  install:
    desc: Installs the required dependencies on pull.
    cmds:
      - yay -S avr-gcc avr-glibc avrdude qmk-udev-rules-git
      - make git-submodule
      - pipenv install

  compile:
    desc: Compile the keyboard/keymap.
    cmds:
      - qmk compile -kb sofle -km cenk1cenk2

  flash:
    desc: Flash the keyboard/keymap.
    cmds:
      - qmk flash -kb sofle -km cenk1cenk2
